spring:
  application:
    name: file
  servlet:
    multipart:
#     文件最大的大小
      max-file-size: 10MB
#      请求最大大小
      max-request-size: 10MB

server:
  port: 18010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
